### ISSUE TITLE
ColumnCount 不能动态变动

### ISSUE THREAD

**Issue by CoderWangP** [dnwalter/FormLayoutManager#10]
@Override
    public int getColumnCount() {
        return 8;
    }

只能是写死的，上面的topAdapter，与下面的MonsterHAdapter不能动态调整ColumnCount

**Comment by dnwalter** [comment]
首先这是一个表格，很少需求表格的列数是不固定的。就算你要动态变，你弄个变量，动态改这个列数，然后再重写getRowData，让它根据不同列数，返回不同的行数据，再刷新不就行了

**Comment by dnwalter** [comment]
> ```
> @Override
> public int getColumnCount() {
>     return 8;
> }
> ```
> 
> 只能是写死的，上面的topAdapter，与下面的MonsterHAdapter不能动态调整ColumnCount

我提了最新代码，里面有个EditFormActivity，参考里面的代码，就知道怎么动态改列数和列顺序了
