### ISSUE TITLE
item复用逻辑好像有问题。

### ISSUE THREAD

**Issue by UI-Animation-Chen** [dnwalter/FormLayoutManager#12]
表格在滑动时，createView仍然会一直调用，itemView复用是不是有问题？

**Comment by dnwalter** [comment]
> 表格在滑动时，createView仍然会一直调用，itemView复用是不是有问题？

我的第一篇博客，其实先建议你去看看一位大神讲解怎么封装自定义LayoutManager，他里面也说了一下RecyclerView的缓存机制。https://blog.csdn.net/harvic880925/article/details/84866486
我简单说一下你的现象。假如你滑的足够快，不管是我的表格还是普通LinearLayoutManager的列表，只要你滑的很快，列表突然要新增的item超过了RecyclerView的mRecyclerPool（一个缓存viewholder的池，最大数量是5），它就会进createViewHolder的方法。但一般普通的列表很少会出现这种请求，因为最大数量是5差不多足够了，除非你的列表的item高度很小，一滑就更新超过5个。
但你也许也会方向我那个表格的即使慢慢滑，也会出现复用。下面我大概说一下：
就拿我的demo第二个界面水平排列表单来说。看着demo可以看出，那个表格一列显示7个格子。这个时候你左右慢慢的滑，表格要展示新的一列的时候，就会进两次createViewHolder。这就是因为我是每个格子都复用，当一下子新增7个在界面上现在，而缓池最大数量是5个，说以就多出两个要新增就进了createViewHolder。而那个表格一开始它一行只显示4个，你只垂直的上下滑，发现它就没有进createViewHolder。（不过建议你试的时候，小心别手抖左右滑了。因为第二个界面没限制单向滑，或者你改一下换成HVSingleRecyclerView，或者用第三个界面垂直排列表单试也行）

**Comment by UI-Animation-Chen** [comment]
> > 表格在滑动时，createView仍然会一直调用，itemView复用是不是有问题？
> 
> 我的第一篇博客，其实先建议你去看看一位大神讲解怎么封装自定义LayoutManager，他里面也说了一下RecyclerView的缓存机制。https://blog.csdn.net/harvic880925/article/details/84866486
> 我简单说一下你的现象。假如你滑的足够快，不管是我的表格还是普通LinearLayoutManager的列表，只要你滑的很快，列表突然要新增的item超过了RecyclerView的mRecyclerPool（一个缓存viewholder的池，最大数量是5），它就会进createViewHolder的方法。但一般普通的列表很少会出现这种请求，因为最大数量是5差不多足够了，除非你的列表的item高度很小，一滑就更新超过5个。
> 但你也许也会方向我那个表格的即使慢慢滑，也会出现复用。下面我大概说一下：
> 就拿我的demo第二个界面水平排列表单来说。看着demo可以看出，那个表格一列显示7个格子。这个时候你左右慢慢的滑，表格要展示新的一列的时候，就会进两次createViewHolder。这就是因为我是每个格子都复用，当一下子新增7个在界面上现在，而缓池最大数量是5个，说以就多出两个要新增就进了createViewHolder。而那个表格一开始它一行只显示4个，你只垂直的上下滑，发现它就没有进createViewHolder。（不过建议你试的时候，小心别手抖左右滑了。因为第二个界面没限制单向滑，或者你改一下换成HVSingleRecyclerView，或者用第三个界面垂直排列表单试也行）

感谢作者的回复。我建议是不是可以把默认缓存调大一点，一维的话缓存5个是足够用的，二维的话就捉襟见肘了。

**Comment by dnwalter** [comment]
> > > 表格在滑动时，createView仍然会一直调用，itemView复用是不是有问题？
> > 
> > 
> > 我的第一篇博客，其实先建议你去看看一位大神讲解怎么封装自定义LayoutManager，他里面也说了一下RecyclerView的缓存机制。https://blog.csdn.net/harvic880925/article/details/84866486
> > 我简单说一下你的现象。假如你滑的足够快，不管是我的表格还是普通LinearLayoutManager的列表，只要你滑的很快，列表突然要新增的item超过了RecyclerView的mRecyclerPool（一个缓存viewholder的池，最大数量是5），它就会进createViewHolder的方法。但一般普通的列表很少会出现这种请求，因为最大数量是5差不多足够了，除非你的列表的item高度很小，一滑就更新超过5个。
> > 但你也许也会方向我那个表格的即使慢慢滑，也会出现复用。下面我大概说一下：
> > 就拿我的demo第二个界面水平排列表单来说。看着demo可以看出，那个表格一列显示7个格子。这个时候你左右慢慢的滑，表格要展示新的一列的时候，就会进两次createViewHolder。这就是因为我是每个格子都复用，当一下子新增7个在界面上现在，而缓池最大数量是5个，说以就多出两个要新增就进了createViewHolder。而那个表格一开始它一行只显示4个，你只垂直的上下滑，发现它就没有进createViewHolder。（不过建议你试的时候，小心别手抖左右滑了。因为第二个界面没限制单向滑，或者你改一下换成HVSingleRecyclerView，或者用第三个界面垂直排列表单试也行）
> 
> 感谢作者的回复。我建议是不是可以把默认缓存调大一点，一维的话缓存5个是足够用的，二维的话就捉襟见肘了。

回复越拼越长了，我告诉你一种临时解决方案，打开网页，看下一条评论

**Comment by dnwalter** [comment]
我解析一下，一般LayoutManager或自定义的，都有回收机制的。即使会有新进入createViewHolder，新建了view，但是这些view超出屏幕的时候，会回收掉的。所以说整个RecyclerView所持有的子view会维持在一个稳定数量的水平，即使缓存最多数量是不是5也没关系。
但可能会出现这种情况，假如你的表格一屏幕一列有100个格子，那么你只是简单左右滑一下，它就要创建95个view会有点稍微耗时，这种情况，快速滚动，很大可能看到滑动不会这么流畅。这种情况可以考虑修改缓存的size。我暂时没把方法写在自己库那里。但RecyclerView有提供类似的方法接口，你有需要可以自己调用。如下：
set最大的缓存size是要传入viewHolderType，这个你看着办。
`       RecyclerView.RecycledViewPool recyclerPool = new RecyclerView.RecycledViewPool();
        recyclerPool.setMaxRecycledViews(0, 10);
        mRecyclerView.setRecycledViewPool(recyclerPool);`
