### ISSUE TITLE
请问支持第一行/第一列，或者前几行/前几列，固定顶部/左侧 不跟随滑动吗？（跟表格一样）

### ISSUE THREAD

**Issue by LiuDongCai** [dnwalter/FormLayoutManager#15]
请问支持第一行/第一列，或者前几行/前几列，固定顶部/左侧 不跟随滑动吗？（跟表格一样）

**Comment by dnwalter** [comment]
> 请问支持第一行/第一列，或者前几行/前几列，固定顶部/左侧 不跟随滑动吗？（跟表格一样）

不好意思，没有。可能你要自己实现了
