### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by hupihuai** [dnwalter/FormLayoutManager#6]
一开始会测量所有View，for (int i = 0; i < getItemCount(); i++) {...} 存在严重的性能问题

**Comment by dnwalter** [comment]
这个没办法，一开始我要计算整个表格的总宽和总高。一开始是不用遍历全部的，前提是你每个格子的宽高都是固定就行了。但后期我改成可以设置不同宽的列后，我就改成这样了。
的确，一般大家的表格宽可能都一样的，那个时候，我应该准备另外一套方法。我新增一个方法，改一下

**Comment by dnwalter** [comment]
> 一开始会测量所有View，for (int i = 0; i < getItemCount(); i++) {...} 存在严重的性能问题

这个没办法，一开始我要计算整个表格的总宽和总高。一开始是不用遍历全部的，前提是你每个格子的宽高都是固定就行了。但后期我改成可以设置不同宽的列后，我就改成这样了。
的确，一般大家的表格宽可能都一样的，那个时候，我应该准备另外一套方法。我新增一个方法，改一下

**Comment by dnwalter** [comment]
> 一开始会测量所有View，for (int i = 0; i < getItemCount(); i++) {...} 存在严重的性能问题

不对哦。好久没看自己代码，差点被你吓到了。你再看一下那段代码。虽然有这么一个循环，但这循环不是测量所有的view。如果你的表格的item宽高都一样，它只会测量一次，剩下的都是用这次测量的宽高来创建Rect
