### ISSUE TITLE
嵌套滑动问题

### ISSUE THREAD

**Issue by Ecgbert** [dnwalter/FormLayoutManager#7]
如题

在bottomsheetbehavior中使用时会存在嵌套滑动问题

recyclerview只能够上滑，无法下滑，bottomsheet会直接折叠起来

**Comment by dnwalter** [comment]
> 如题
> 
> 在bottomsheetbehavior中使用时会存在嵌套滑动问题
> 
> recyclerview只能够上滑，无法下滑，bottomsheet会直接折叠起来

我没试过bottomsheetbehavior嵌套RecyclerView的需求。bottomsheetbehavior嵌套普通的RecyclerView上下滑正不正常。因为我都没改过RecyclerView。如果普通的RecyclerView嵌套能正常，那就是我的问题了

**Comment by Ecgbert** [comment]
我试过了，这与RecyclerView自身无关，我试过LinearLayoutManager跟GridLayoutManager都正常

个人认为问题出在bottomsheetbehavior会判断触摸的这个View能不能滑动
bottomsheetbehavior的内部实现方法是藉由View.canScrollVertically(-1)来判断说这个View是否已经滑到顶端，
但使用你的layoutManager会永远回传false，会导致bottomsheetbehavior认为这个view已经滑到顶了，下拉就直接折叠起来

我只是我初步的判断，不过小弟太菜，还不知道怎么修复，希望大佬能修复这个问题

补充一下 似乎只要是能够同时水平和垂直滑动的LayoutManager 似乎都会碰到这问题，或许跟无法确认确切的滑动方向有关

**Comment by dnwalter** [comment]
> 如题
> 
> 在bottomsheetbehavior中使用时会存在嵌套滑动问题
> 
> recyclerview只能够上滑，无法下滑，bottomsheet会直接折叠起来

我看了一下，可能是我的FormLayoutManager滑的时候是通过将每个item的位置变化，而其他LayoutManager是真的让RecyclerView滑起来，这个改起来有点麻烦。
但是我可以想到一个解决方案，自定义一个RecyclerView重写他的canScrollVertically方法。这个代码我就不提到主分支，我提到了一个osy-issues分支，你可以检出来，看看里面的IssuesActivity类

**Comment by dnwalter** [comment]
> 如题
> 
> 在bottomsheetbehavior中使用时会存在嵌套滑动问题
> 
> recyclerview只能够上滑，无法下滑，bottomsheet会直接折叠起来

之前教你的临时解决方案可以不用了。我看了一下LinearLayoutManager的源码，修改了一下自己的FormLayoutManager，问题已经解决了。你直接更新到v3.1的包就ok了

**Comment by Ecgbert** [comment]
> > 如题
> > 在bottomsheetbehavior中使用时会存在嵌套滑动问题
> > recyclerview只能够上滑，无法下滑，bottomsheet会直接折叠起来
> 
> 之前教你的临时解决方案可以不用了。我看了一下LinearLayoutManager的源码，修改了一下自己的FormLayoutManager，问题已经解决了。你直接更新到v3.1的包就ok了

我昨天刚好也解决了这问题，跟你一样的解法，
今天原本收工前要发上来的，没想到你就先发上来了哈哈
还是多谢大佬帮忙

**Comment by dnwalter** [comment]
我发现还是有点问题，我不知道你有没有用这个HVSingleRecylerView，如果用了的话，会发现先向上滚一点，然后水平滚动的时候，手指不要松开，下滑，就会出现之前嵌套那种情况。不过在v3.2我改了一下HVSingleRecylerView，也改好了。
